app = 'audiohub-db'
primary_region = 'lax'

[build]

[http_service]
    internal_port = 8000
    force_https = true
    auto_stop_machines = 'stop'
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

[[services]]
    internal_port = 8000
    protocol = "tcp"

    [[services.ports]]
        port = 443
        handlers = ["tls", "http"]

    [[services.ports]]
        port = 80
        handlers = ["http"]

[[vm]]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1